/* ---------------------------------------------*/
/*  Generated by PostgreSQL Version 7.8 		*/
/*  Created By CHETAN  					        */
/*  Created On : 05-ott-2024  					*/
/*  DBMS       : PostgreSQL 					*/
/* -------------------------------------------- */

-- Table: public.routes

-- DROP TABLE IF EXISTS public.routes;

CREATE TABLE IF NOT EXISTS public.routes
(
    id_route bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_point character varying(255) COLLATE pg_catalog."default",
    dt_recordedattime date,
    start_point character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT routes_pkey PRIMARY KEY (id_route)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.routes
    OWNER to postgres;