/* ---------------------------------------------*/
/*  Generated by PostgreSQL Version 7.8 		*/
/*  Created By CHETAN  					        */
/*  Created On : 05-ott-2024  					*/
/*  DBMS       : PostgreSQL 					*/
/* -------------------------------------------- */

-- Table: public.shipments

-- DROP TABLE IF EXISTS public.shipments;

CREATE TABLE IF NOT EXISTS public.shipments
(
    id_shipment bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_date date,
    destination character varying(255) COLLATE pg_catalog."default",
    item_name character varying(255) COLLATE pg_catalog."default",
    origin character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    tracking_number character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT shipments_pkey PRIMARY KEY (id_shipment)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shipments
    OWNER to postgres;