/* ---------------------------------------------*/
/*  Generated by PostgreSQL Version 7.8 		*/
/*  Created By CHETAN  					        */
/*  Created On : 05-ott-2024  					*/
/*  DBMS       : PostgreSQL 					*/
/* -------------------------------------------- */

-- Table: public.vehicles

-- DROP TABLE IF EXISTS public.vehicles;

CREATE TABLE IF NOT EXISTS public.vehicles
(
    id_vehcile bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    current_location character varying(255) COLLATE pg_catalog."default",
    id_driver character varying(255) COLLATE pg_catalog."default",
    dt_recordedattime date,
    CONSTRAINT vehicles_pkey PRIMARY KEY (id_vehcile)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.vehicles
    OWNER to postgres;