/* ---------------------------------------------*/
/*  Generated by PostgreSQL Version 7.8 		*/
/*  Created By CHETAN  					        */
/*  Created On : 05-ott-2024  					*/
/*  DBMS       : PostgreSQL 					*/
/* -------------------------------------------- */

-- Table: public.weatherdata

-- DROP TABLE IF EXISTS public.weatherdata;

CREATE TABLE IF NOT EXISTS public.weatherdata
(
    id_weatherdata bigint NOT NULL,
    dsc_weather character varying COLLATE pg_catalog."default",
    temperature numeric(5,3),
    retrieved_at date,
    id_route bigint,
    CONSTRAINT weatherdata_pkey PRIMARY KEY (id_weatherdata),
    CONSTRAINT weatherdata_routes_fkey FOREIGN KEY (id_route)
        REFERENCES public.routes (id_route) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.weatherdata
    OWNER to postgres;